name: Ürünleri Güncelle

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu al
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Gereksinimleri kur
      run: pip install requests

    - name: Ürün verisini çek
      run: python scripts/urun_tarayici.py

    - name: Değişiklikleri kaydet ve push et
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git pull origin master --rebase
        git add .
        git commit -m "JSON güncellendi" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
